<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-17 at 16:00:08.
 */
class WelcomeControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var WelcomeController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WelcomeController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
