<?php


/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-16 at 20:06:37.
 */
class LoggerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Logger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = \Logger::getInstance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Logger::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Logger::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Logger::setLogFile
     * @todo   Implement testSetLogFile().
     */
    public function testSetLogFile() {
        $this->object->setLogFile('testlog.txt');
        $this->assertNotFalse($this->object->getFile_handle());
        var_dump($this->object->getFile_handle());
    }

    /**
     * @covers Logger::setPriority
     * @todo   Implement testSetPriority().
     */
    public function testSetPriority() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  @depends testSetLogFile
     * @covers Logger::logInfo
     * @todo   Implement testLogInfo().
     */
    public function testLogInfo() {
        $this->object->logInfo('Info line');
    }

    /**
     * @covers Logger::logDebug
     * @todo   Implement testLogDebug().
     */
    public function testLogDebug() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Logger::LlogWarn
     * @todo   Implement testLlogWarn().
     */
    public function testLlogWarn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Logger::logError
     * @todo   Implement testLogError().
     */
    public function testLogError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Logger::logFatal
     * @todo   Implement testLogFatal().
     */
    public function testLogFatal() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Logger::log
     * @todo   Implement testLog().
     */
    public function testLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @depends testSetLogFile
     * @covers Logger::WriteFreeFormLine
     * @todo   Implement testWriteFreeFormLine().
     */
    public function testWriteFreeFormLine() {
        $this->object->WriteFreeFormLine('some text to write');
    }

}
