<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-19 at 07:56:13.
 */
class RequestHandlerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var RequestHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new RequestHandler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RequestHandler::isEmpty
     * @todo   Implement testIsEmpty().
     */
    public function testIsEmpty() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RequestHandler::isGet
     * @todo   Implement testIsGet().
     */
    public function testIsGet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RequestHandler::isPost
     * @todo   Implement testIsPost().
     */
    public function testIsPost() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RequestHandler::getRequest
     * @todo   Implement testGetRequest().
     */
    public function testGetRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RequestHandler::postRequest
     * @todo   Implement testPostRequest().
     */
    public function testPostRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
