<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-01 at 09:50:51.
 */
class SeseSessionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SeseSession
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SeseSession;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SeseSession::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SeseSession::getDebugInstance
     * @todo   Implement testGetDebugInstance().
     */
    public function testGetDebugInstance() {
        $session = $this->object->getDebugInstance();
        $session->setName('unit_test_debug_session');
        $session->start();
        $session->set('unit_test_debug_session', 'started');
        $this->assertTrue($session->isStarted());
        $this->assertEquals('started', $session->get('unit_test_debug_session'));
    }

}
