<?php

namespace Model\Dal\DbLibrary;

//tables for tests
use Model\Dal\ModelDb\Enseignant\EnseignantObject;
use Model\Dal\ModelDb\Utilisateurs\UtilisateursObject;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-26 at 22:26:46.
 */
class DataAccessTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DataAccess
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new DataAccess;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::GetDbAccess
     * @todo   Implement testGetDbAccess().
     */
    public function testGetDbAccess() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::Insert
     * @todo   Implement testInsert().
     */
    public function testInsert() {
        $this->object = new DataAccess('Enseignant');
        $teacher = new EnseignantObject;
        $teacher->ens_prenom_enseignant = 'laurent';
        $teacher->ens_nom_enseignant = 'authier';
        $teacher->ens_mel_enseignant = 'laurent@moi.org';
        $teacher->ens_discipline = 'programmation';
        $this->object->Insert($teacher);
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::Update
     * @depends testInsert
     */
    public function testUpdate() {
        $this->object = new DataAccess('Enseignant');
        //$teacher = $this->object->GetAll();
        //$teacher = end($all);
        $teacher = $this->object->GetByColumnValue('ens_nom_enseignant', 'authier');
        $id = $teacher->id_enseignant;
        $teacher->ens_prenom_enseignant = 'super laurent 2015';
        $teacher->ens_nom_enseignant = 'mon nom';
        $teacher->ens_mel_enseignant = 'superlaurent@moi.org';
        $teacher->ens_discipline = 'xxxxxxxxx';
        $this->object->Update($teacher);
        $t = $this->object->GetByID($id);
        $this->assertEquals('super laurent 2015',$t->ens_prenom_enseignant );
    }
    
    
    /**
     * Update table avec clés composites
     * @covers Model\Dal\DbLibrary\DataAccess::Update
     * @depends testInsert
     */
    public function testUpdateWithSelector() {
        $this->object = new DataAccess('Constituer');
        $link= $this->object->GetByCompositeKeys(array('id_competence'=>910, 'id_activite'=>419));
        $this->assertNotFalse($link);
        $self= array('id_competence_SELF'=>910,'id_activite_SELF'=>419);
        $link->id_activite = 418;
        $this->assertNotFalse($this->object->InnerSelfUpdate($link,$self));
        $this->assertNotFalse($link= $this->object->GetByCompositeKeys((array('id_competence'=>910, 'id_activite'=>418))));
    }
    
    /**
     * @covers Model\Dal\DbLibrary\DataAccess::Update
     * @depends testInsert
     */
    public function testUpdate4() {
        $this->object = new DataAccess('Promotion');
        $item = $this->object->GetByID(3);
        //var_dump($item);
        $item->pro_reference_promotion= 'SUPER SEN';
//        
      
        $this->object->Update($item);

    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::Delete
     * @todo   Implement testDelete().
     */
    public function testDelete() {
        $this->object = new DataAccess('Enseignant');
        $all=$teacher = $this->object->GetAll();
        $teacher = end($all);
        $this->object->Delete($teacher);
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::GetAll
     * @todo   Implement testGetAll().
     */
    public function testGetAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::GetByID
     * @todo   Implement testGetByID().
     */
    public function testGetByID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::GetByCompositeKeys
     * @todo   Implement testGetByCompositeKeys().
     */
    public function testGetByCompositeKeys() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::GetByColumnValue
     * @depends testUpdate
     */
    public function testGetByColumnValue() {
        $this->object = new DataAccess('Enseignant'); 
        $var = 'superlaurent@moi.org';
        $r = $this->object->GetByColumnValue('ens_mel_enseignant', $var);
        //var_dump($r);
        $this->assertNotFalse($r);
    }
    
    public function testGetByColumnValue_nullValue() {
        $this->object = new DataAccess('Enseignant');
        $var = null;
        $r = $this->object->GetByColumnValue('ens_mel_enseignant', $var);
        //var_dump($r);
        $this->assertFalse($r);
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::GetAllByColumnValue
     * @todo   Implement testGetAllByColumnValue().
     */
    public function testGetAllByColumnValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    
    
    public function testIsValidForeignKey(){
        $this->object = new DataAccess('Fonction');
        $all = $this->object->GetAll();
        $this->assertTrue($this->object->isValidForeignKey($all[0]));
        //fonction non liée à une autre table
        $this->assertFalse($this->object->isValidForeignKey(end($all)));

    }
    
    public function testXXX(){
        $ct=new b();
        $this->assertEquals('toto', $ct->t);
        $this->assertEquals('titi', $ct->u);
    }

}

class a{
    public $t='toto';
}

class b extends a{
    public $u='titi';
    
    
}

