<?php

namespace Model\Dal\DbLibrary;

//tables for tests
use Model\Dal\ModelDb\Enseignant\EnseignantObject;
use Model\Dal\ModelDb\Utilisateurs\UtilisateursObject;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-26 at 22:26:46.
 */
class DataAccessTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DataAccess
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new DataAccess;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::GetDbAccess
     * @todo   Implement testGetDbAccess().
     */
    public function testGetDbAccess() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::Insert
     * @todo   Implement testInsert().
     */
    public function testInsert() {
        $this->object = new DataAccess('Enseignant');
        $teacher = new EnseignantObject;
        $teacher->ens_prenom_enseignant = 'laurent';
        $teacher->ens_nom_enseignant = 'authier';
        $teacher->ens_mel_enseignant = 'laurent@moi.org';
        $teacher->ens_discipline = 'programmation';
        $this->object->Insert($teacher);
        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::Update
     * @depends testInsert
     */
    public function testUpdate() {
        $this->object = new DataAccess('Enseignant');
        $all = $this->object->GetAll();
        $teacher = end($all);
        //var_dump($teacher);
        $teacher->ens_prenom_enseignant = 'super laurent';
        $teacher->ens_nom_enseignant = 'super authier';
        $teacher->ens_mel_enseignant = 'superlaurent@moi.org';
        $teacher->ens_discipline = 'super programmation';
        $this->object->Update($teacher);
        
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::Delete
     * @todo   Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::GetAll
     * @todo   Implement testGetAll().
     */
    public function testGetAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::GetByID
     * @todo   Implement testGetByID().
     */
    public function testGetByID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::GetByCompositeKeys
     * @todo   Implement testGetByCompositeKeys().
     */
    public function testGetByCompositeKeys() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::GetByColumnValue
     * @depends testUpdate
     */
    public function testGetByColumnValue() {
        $this->object = new DataAccess('Enseignant');
        $var = 'superlaurent@moi.org';
        $r=$this->object->GetByColumnValue('ens_mel_enseignant', $var);
        //var_dump($r);
        $this->assertNotFalse($r);
    }

    /**
     * @covers Model\Dal\DbLibrary\DataAccess::GetAllByColumnValue
     * @todo   Implement testGetAllByColumnValue().
     */
    public function testGetAllByColumnValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
