<?php

namespace Model;

use UserConnected;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-18 at 18:21:54.
 */
class DisplayDocumentModelTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DisplayDocumentModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DisplayDocumentModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Model\DisplayDocumentModel::get_documentList
     * @todo   Implement testGet_documentList().
     */
    public function testGet_documentList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DisplayDocumentModel::set_documentList
     * @todo   Implement testSet_documentList().
     */
    public function testSet_documentList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DisplayDocumentModel::addBlank
     * @todo   Implement testAddBlank().
     */
    public function testAddBlank() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DisplayDocumentModel::append
     * @todo   Implement testAppend().
     */
    public function testAppend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DisplayDocumentModel::deleteFromId
     * @todo   Implement testDeleteFromId().
     */
    public function testDeleteFromId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DisplayDocumentModel::deleteFromProperty
     * @todo   Implement testDeleteFromProperty().
     */
    public function testDeleteFromProperty() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DisplayDocumentModel::getAll
     * @todo   Implement testGetAll().
     */
    public function testGetAll() {
        $user=  UserConnected::getInstance();
        $user->setUserName('t@t');
        $user->setUserGroup('tuteur');
        $this->object->getAll();
    }

    /**
     * @covers Model\DisplayDocumentModel::resetModel
     * @todo   Implement testResetModel().
     */
    public function testResetModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DisplayDocumentModel::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
