<?php

namespace Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-17 at 14:14:23.
 */
class DocumentDefinitionModelTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DocumentDefinitionModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DocumentDefinitionModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Model\DocumentDefinitionModel::get_documentTypeList
     * @todo   Implement testGet_documentTypeList().
     */
    public function testGet_documentTypeList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::get_readerList
     * @todo   Implement testGet_readerList().
     */
    public function testGet_readerList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::get_docList
     * @todo   Implement testGet_docList().
     */
    public function testGet_docList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::get_documentContent
     * @todo   Implement testGet_documentContent().
     */
    public function testGet_documentContent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::get_documentSubject
     * @todo   Implement testGet_documentSubject().
     */
    public function testGet_documentSubject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::get_access
     * @todo   Implement testGet_access().
     */
    public function testGet_access() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::set_documentType
     * @todo   Implement testSet_documentType().
     */
    public function testSet_documentType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::set_docName
     * @todo   Implement testSet_docName().
     */
    public function testSet_docName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::set_newDocName
     * @todo   Implement testSet_newDocName().
     */
    public function testSet_newDocName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::set_access
     * @todo   Implement testSet_access().
     */
    public function testSet_access() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::set_documentContent
     * @todo   Implement testSet_documentContent().
     */
    public function testSet_documentContent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::addBlank
     * @todo   Implement testAddBlank().
     */
    public function testAddBlank() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::append
     * @todo   Implement testAppend().
     */
    public function testAppend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::deleteFromId
     * @todo   Implement testDeleteFromId().
     */
    public function testDeleteFromId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::deleteFromProperty
     * @todo   Implement testDeleteFromProperty().
     */
    public function testDeleteFromProperty() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::getAll
     * @todo   Implement testGetAll().
     */
    public function testGetAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::resetModel
     * @todo   Implement testResetModel().
     */
    public function testResetModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::getDocList
     * @todo   Implement testGetDocList().
     */
    public function testGetDocList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\DocumentDefinitionModel::updateAccessToDoc
     * @todo   Implement testUpdateAccessToDoc().
     */
    public function testUpdateAccessToDoc() {
        $this->object->set_access('stagiaire', 'stagiaire');
        $this->object->updateAccessToDoc('sujet test');
    }

}
