<?php

namespace Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-15 at 11:56:44.
 */
class HeaderModelTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HeaderModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HeaderModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Model\HeaderModel::get_schoolName
     * @todo   Implement testGet_schoolName().
     */
    public function testGet_schoolName() {
        $this->assertEquals('',$this->object->get_schoolName()); 
       
    }

    /**
     * @covers Model\HeaderModel::get_courseName
     * @todo   Implement testGet_courseName().
     */
    public function testGet_courseName() {
        $this->assertEquals('',$this->object->get_courseName()); 
    }

    /**
     * @covers Model\HeaderModel::get_studyYear
     * @todo   Implement testGet_studyYear().
     */
    public function testGet_studyYear() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\HeaderModel::get_userName
     * @todo   Implement testGet_userName().
     */
    public function testGet_userName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\HeaderModel::get_userRole
     * @todo   Implement testGet_userRole().
     */
    public function testGet_userRole() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
