<?php

namespace Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-11 at 18:08:06.
 */
class LoginModelTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var LoginModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LoginModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testIsUserKnown() {
        $this->assertFalse($this->object->isUserKnown());
        $this->object->set_userName('dieu');
        $this->object->set_userPass('dieu');
        $this->assertTrue($this->object->isUserKnown());
        $this->object->set_userName('dieu');
        $this->object->set_userPass('paradis');
        $this->assertFalse($this->object->isUserKnown());
        $this->object->set_userName('lolo');
        $this->object->set_userPass('laurent');
        $this->assertTrue($this->object->isUserKnown());
    }
    
    public function testHashPassword(){
        //ok
        $hash= password_hash('laurent', PASSWORD_BCRYPT);
        echo $hash;
        $this->assertTrue(password_verify('laurent', $hash));
        //ko
        $this->assertFalse(password_verify('martin', $hash));

    }

}
