<?php

namespace Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-21 at 19:18:36.
 */
class PromotionModelTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var PromotionModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PromotionModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Model\PromotionModel::get_references
     * @todo   Implement testGet_references().
     */
    public function testGet_references() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\PromotionModel::get_descriptions
     * @todo   Implement testGet_descriptions().
     */
    public function testGet_descriptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\PromotionModel::set_references
     * @todo   Implement testSet_references().
     */
    public function testSet_references() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\PromotionModel::set_descriptions
     * @todo   Implement testSet_descriptions().
     */
    public function testSet_descriptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\PromotionModel::addBlankToViewModel
     * @todo   Implement testAddBlankToViewModel().
     */
    public function testAddBlankToViewModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\PromotionModel::getAllPromotions
     * @todo   Implement testGetAllPromotions().
     */
    public function testGetAllPromotions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\PromotionModel::appendPromotion
     * @todo   Implement testAppendPromotion().
     */
    public function testAppendPromotion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\PromotionModel::addPromotion
     * @todo   Implement testAddPromotion().
     */
    public function testAddPromotion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\PromotionModel::delPromotion
     * @todo   Implement testDelPromotion().
     */
    public function testDelPromotion() {
        $this->object->delPromotion('ref2015');
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\PromotionModel::updatePromotion
     * @todo   Implement testUpdatePromotion().
     */
    public function testUpdatePromotion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
