<?php

namespace Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-23 at 10:45:03.
 */
class TutorTraineeListModelTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TutorTraineeListModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->setupSession();
        $this->object = new TutorTraineeListModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }
    
    public function setupSession(){
        $session=\SeseSession::getDebugInstance();
        $session->setName('test SESE');
        $session->start();
        $session->set('user_connected/name','t@t');
    }

    /**
     * @covers Model\WelcomeTutorModel::get_visitsInfos
     * @todo   Implement testGet_visitsInfos().
     */
    public function testGet_visitsInfos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WelcomeTutorModel::getAllVisits
     * @todo   Implement testGetAllVisits().
     */
    public function testgetAllTrainee() {
        $this->object->getAll();
        $r=$this->object->get_traineeList();
        var_dump($r);
        $this->assertEquals(array(), $r );
        
    }

    /**
     * @covers Model\WelcomeTutorModel::convertMysqlToFrDate
     * @todo   Implement testConvertMysqlToFrDate().
     */
    public function testConvertMysqlToFrDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    
    public function testgetWorkPeriod(){
        $id=5;
        $this->assertEquals('',$this->object->getWorkPeriod($id));
        
    }

}
