<?php

namespace Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-13 at 15:56:29.
 */
class TutorEvaluateSkillTraineeModelTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TutorEvaluateSkillTraineeModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $user = \UserConnected::getInstance();
        $user->setUserName('t@t');
        $user->setUserGroup('t@t');
        $this->object = new TutorEvaluateSkillTraineeModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Model\TutorEvaluateSkillTraineeModel::get_functionList
     * @todo   Implement testGet_functionList().
     */
    public function testGet_functionList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\TutorEvaluateSkillTraineeModel::get_autonomyList
     * @todo   Implement testGet_autonomyList().
     */
    public function testGet_autonomyList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\TutorEvaluateSkillTraineeModel::addBlank
     * @todo   Implement testAddBlank().
     */
    public function testAddBlank() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\TutorEvaluateSkillTraineeModel::append
     * @todo   Implement testAppend().
     */
    public function testAppend() {
        $this->object->buildTraineeList();
        $al=$this->object->get_traineeList();
        $this->object->set_traineeName(reset($al));
        $this->object->append();
        
    }

    public function testisTraineeEvaluated(){
        $this->assertTrue($this->object->isTraineeEvaluated(5));
    }
    
    public function testgetReorderedList(){
        $l = array(0=>'b','c','d','a');
        $this->assertEquals(array('a', 'b','c','d'), $this->object->getReorderedList(3, $l));
    }
    
    /**
     * @covers Model\TutorEvaluateSkillTraineeModel::deleteFromId
     * @todo   Implement testDeleteFromId().
     */
    public function testDeleteFromId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\TutorEvaluateSkillTraineeModel::deleteFromProperty
     * @todo   Implement testDeleteFromProperty().
     */
    public function testDeleteFromProperty() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\TutorEvaluateSkillTraineeModel::getAll
     * @todo   Implement testGetAll().
     */
    public function testGetAll() {
        $this->object->getAll();
        //var_dump($this->object->get_functionList());
    }

    /**
     * @covers Model\TutorEvaluateSkillTraineeModel::resetModel
     * @todo   Implement testResetModel().
     */
    public function testResetModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\TutorEvaluateSkillTraineeModel::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\TutorEvaluateSkillTraineeModel::buildFunctionlist
     * @todo   Implement testBuildFunctionlist().
     */
    public function testBuildFunctionlist() {
        $this->object->buildFunctionlist(5);
       var_dump($this->object->get_functionList());
    }

    /**
     * @covers Model\TutorEvaluateSkillTraineeModel::buildSkillsLevels
     * @todo   Implement testBuildSkillsLevels().
     */
    public function testBuildSkillsLevels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\TutorEvaluateSkillTraineeModel::buildAutonomyLevels
     * @todo   Implement testBuildAutonomyLevels().
     */
    public function testBuildAutonomyLevels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
