<?php

namespace Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-22 at 15:50:44.
 */
class WelcomeTutorModelTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var WelcomeTutorModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WelcomeTutorModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Model\WelcomeTutorModel::get_visitsInfos
     * @todo   Implement testGet_visitsInfos().
     */
    public function testGet_visitsInfos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WelcomeTutorModel::getAllVisits
     * @todo   Implement testGetAllVisits().
     */
    public function testGetAllVisits() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WelcomeTutorModel::convertMysqlToFrDate
     * @todo   Implement testConvertMysqlToFrDate().
     */
    public function testConvertMysqlToFrDate() {
        $date = "2015-04-22";
        $this->assertEquals('',$this->object->convertMysqlToFrDate($date));
    }

}
