<?php

namespace Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-29 at 21:55:00.
 */
class WorkDefinitionModelTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var WorkDefinitionModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WorkDefinitionModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Model\WorkDefinitionModel::get_workNameList
     * @todo   Implement testGet_workNameList().
     */
    public function testGet_workNameList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_traineeList
     * @todo   Implement testGet_traineeList().
     */
    public function testGet_traineeList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_teacherList
     * @todo   Implement testGet_teacherList().
     */
    public function testGet_teacherList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_companyList
     * @todo   Implement testGet_companyList().
     */
    public function testGet_companyList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_companyName
     * @todo   Implement testGet_companyName().
     */
    public function testGet_companyName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_companyActivity
     * @todo   Implement testGet_companyActivity().
     */
    public function testGet_companyActivity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_companySiret
     * @todo   Implement testGet_companySiret().
     */
    public function testGet_companySiret() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_companyAddress
     * @todo   Implement testGet_companyAddress().
     */
    public function testGet_companyAddress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_companyCity
     * @todo   Implement testGet_companyCity().
     */
    public function testGet_companyCity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_companyZip
     * @todo   Implement testGet_companyZip().
     */
    public function testGet_companyZip() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_companyPhone
     * @todo   Implement testGet_companyPhone().
     */
    public function testGet_companyPhone() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_companyEmail
     * @todo   Implement testGet_companyEmail().
     */
    public function testGet_companyEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_employeeList
     * @todo   Implement testGet_employeeList().
     */
    public function testGet_employeeList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_employeeLastName
     * @todo   Implement testGet_employeeLastName().
     */
    public function testGet_employeeLastName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_employeeFirstName
     * @todo   Implement testGet_employeeFirstName().
     */
    public function testGet_employeeFirstName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_employeePhone
     * @todo   Implement testGet_employeePhone().
     */
    public function testGet_employeePhone() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_employeeEmail
     * @todo   Implement testGet_employeeEmail().
     */
    public function testGet_employeeEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::get_employeeRole
     * @todo   Implement testGet_employeeRole().
     */
    public function testGet_employeeRole() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_workNameList
     * @todo   Implement testSet_workNameList().
     */
    public function testSet_workNameList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_traineeList
     * @todo   Implement testSet_traineeList().
     */
    public function testSet_traineeList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_teacherList
     * @todo   Implement testSet_teacherList().
     */
    public function testSet_teacherList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_companyList
     * @todo   Implement testSet_companyList().
     */
    public function testSet_companyList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_companyName
     * @todo   Implement testSet_companyName().
     */
    public function testSet_companyName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_companyActivity
     * @todo   Implement testSet_companyActivity().
     */
    public function testSet_companyActivity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_companySiret
     * @todo   Implement testSet_companySiret().
     */
    public function testSet_companySiret() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_companyAddress
     * @todo   Implement testSet_companyAddress().
     */
    public function testSet_companyAddress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_companyCity
     * @todo   Implement testSet_companyCity().
     */
    public function testSet_companyCity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_companyZip
     * @todo   Implement testSet_companyZip().
     */
    public function testSet_companyZip() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_companyPhone
     * @todo   Implement testSet_companyPhone().
     */
    public function testSet_companyPhone() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_companyEmail
     * @todo   Implement testSet_companyEmail().
     */
    public function testSet_companyEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_employeeList
     * @todo   Implement testSet_employeeList().
     */
    public function testSet_employeeList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_employeeLastName
     * @todo   Implement testSet_employeeLastName().
     */
    public function testSet_employeeLastName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_employeeFirstName
     * @todo   Implement testSet_employeeFirstName().
     */
    public function testSet_employeeFirstName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_employeePhone
     * @todo   Implement testSet_employeePhone().
     */
    public function testSet_employeePhone() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_employeeEmail
     * @todo   Implement testSet_employeeEmail().
     */
    public function testSet_employeeEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::set_employeeRole
     * @todo   Implement testSet_employeeRole().
     */
    public function testSet_employeeRole() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    
    /**
     * @covers Model\WorkDefinitionModel::getAll
     * @todo   Implement testGetAll().
     */
    public function testGetAll() {
        $this->object->getAll();
    }

    /**
     * @covers Model\WorkDefinitionModel::addBlank
     * @todo   Implement testAddBlank().
     */
    public function testAddBlank() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::append
     * @todo   Implement testAppend().
     */
    public function testAppend() {
        $this->object->set_companyActivity("test company activity");
        $this->object->set_companyName('test company');
        $this->object->set_employeeFirstName('employee test');
        $this->object->set_employeeRole('employee role test');
        $this->object->append();
        $this->object->getAll();
        
        
                
        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
    }

    /**
     * @covers Model\WorkDefinitionModel::deleteFromId
     * @todo   Implement testDeleteFromId().
     */
    public function testDeleteFromId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::deleteFromProperty
     * @todo   Implement testDeleteFromProperty().
     */
    public function testDeleteFromProperty() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    

    /**
     * @covers Model\WorkDefinitionModel::resetModel
     * @todo   Implement testResetModel().
     */
    public function testResetModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::getAllWorkName
     * @todo   Implement testGetAllWorkName().
     */
    public function testGetAllWorkName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::getAllTrainees
     * @todo   Implement testGetAllTrainees().
     */
    public function testGetAllTrainees() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::getAllTeachers
     * @todo   Implement testGetAllTeachers().
     */
    public function testGetAllTeachers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::getAllCompanies
     * @todo   Implement testGetAllCompanies().
     */
    public function testGetAllCompanies() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::getAllEmployees
     * @todo   Implement testGetAllEmployees().
     */
    public function testGetAllEmployees() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::delWork
     * @todo   Implement testDelWork().
     */
    public function testDelWork() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::addCompany
     * @todo   Implement testAddCompany().
     */
    public function testAddCompany() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::addEmployee
     * @todo   Implement testAddEmployee().
     */
    public function testAddEmployee() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkDefinitionModel::addToTable
     * @todo   Implement testAddToTable().
     */
    public function testAddToTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
