<?php

namespace Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-01 at 15:14:37.
 */
class WorkVisitDefinitionModelTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var WorkVisitDefinitionModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WorkVisitDefinitionModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Model\WorkVisitDefinitionModel::get_visits
     * @todo   Implement testGet_visits().
     */
    public function testGet_visits() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkVisitDefinitionModel::set_visits
     * @todo   Implement testSet_visits().
     */
    public function testSet_visits() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkVisitDefinitionModel::addBlank
     * @todo   Implement testAddBlank().
     */
    public function testAddBlank() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkVisitDefinitionModel::append
     * @todo   Implement testAppend().
     */
    public function testAppend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkVisitDefinitionModel::deleteFromId
     * @todo   Implement testDeleteFromId().
     */
    public function testDeleteFromId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkVisitDefinitionModel::deleteFromProperty
     * @todo   Implement testDeleteFromProperty().
     */
    public function testDeleteFromProperty() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkVisitDefinitionModel::getAll
     * @todo   Implement testGetAll().
     */
    public function testGetAll() {
        //$this->object->getAll();//session conflict...
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkVisitDefinitionModel::resetModel
     * @todo   Implement testResetModel().
     */
    public function testResetModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model\WorkVisitDefinitionModel::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
